export const HistoryData = [
  {
    id: "1",
    service: "Web Design",
    status: false,
    cust_name: "William Peter",
    price: 250,
    date: "2022-01-10",
  },
  {
    id: "2",
    service: "Icon Design",
    status: false,
    cust_name: "Siti Amirah",
    price: 500,
    date: "2022-01-08",
  },
  {
    id: "3",
    service: "Flyer Design",
    status: false,
    cust_name: "Jake Paul",
    price: 300,
    date: "2022-01-04",
  },
  {
    id: "4",
    service: "App Design",
    status: true,
    cust_name: "Tom Holland",
    price: 1100,
    date: "2022-01-03",
  },
  {
    id: "5",
    service: "Web Design",
    status: false,
    cust_name: "Tony Stark",
    price: 110,
    date: "2021-12-29",
  },
  {
    id: "6",
    service: "UX Design",
    status: false,
    cust_name: "Peter Parker",
    price: 850,
    date: "2021-12-22",
  },
  {
    id: "7",
    service: "UX Design",
    status: true,
    cust_name: "Eric Cheah",
    price: 750,
    date: "2021-12-14",
  },
  {
    id: "8",
    service: "Poster Design",
    status: true,
    cust_name: "Abu Bakar",
    price: 2000,
    date: "2021-12-05",
  },
  {
    id: "9",
    service: "Icon Design",
    status: true,
    cust_name: "Muthu Roti Canai",
    price: 900,
    date: "2021-11-26",
  },
  {
    id: "10",
    service: "App Design",
    status: true,
    cust_name: "Tan Teik Sean",
    price: 150,
    date: "2021-11-13",
  },
  {
    id: "11",
    service: "Photoshop Editing",
    status: true,
    cust_name: "Tom Holland",
    price: 50,
    date: "2021-11-04",
  },
  {
    id: "12",
    service: "App Design",
    status: true,
    cust_name: "The Hulk",
    price: 200,
    date: "2021-10-22",
  },
  {
    id: "13",
    service: "Software UI Refresh",
    status: true,
    cust_name: "Black Widow",
    price: 450,
    date: "2021-10-18",
  },
  {
    id: "14",
    service: "App Design",
    status: true,
    cust_name: "William Peter",
    price: 1500,
    date: "2021-10-11",
  },
  {
    id: "15",
    service: "Web Design",
    status: true,
    cust_name: "Muthu Roti Canai",
    price: 990,
    date: "2021-10-04",
  },
  {
    id: "16",
    service: "Photoshop Editing",
    status: true,
    cust_name: "Siti Amirah",
    price: 560,
    date: "2021-09-30",
  },
  {
    id: "17",
    service: "UX Design",
    status: true,
    cust_name: "Tan Teik Sean",
    price: 90,
    date: "2021-09-26",
  },
  {
    id: "18",
    service: "Software UI Refresh",
    status: true,
    cust_name: "Peter Parker",
    price: 880,
    date: "2021-09-14",
  },
  {
    id: "19",
    service: "App Design",
    status: true,
    cust_name: "Eric Cheah",
    price: 240,
    date: "2021-09-06",
  },
  {
    id: "20",
    service: "Icon Design",
    status: true,
    cust_name: "Tony Stark",
    price: 500,
    date: "2021-08-11",
  },
];
